#Requires -Version 5.1
<#
.SYNOPSIS
    Installs postmortem - instant incident timelines from your git repository.

.DESCRIPTION
    Creates an isolated Python virtualenv at $HOME\.postmortem, installs
    postmortem into it, and adds a wrapper script to $HOME\.local\bin so
    you can run "postmortem" from any terminal.

    If run from a local clone (dev mode), installs in editable mode so
    source changes apply instantly - no reinstall needed.

.PARAMETER Uninstall
    Remove postmortem and all its files.

.EXAMPLE
    # Install (remote)
    irm https://raw.githubusercontent.com/phlx0/postmortem/main/install.ps1 | iex

    # Install (local clone - editable/dev mode)
    .\install.ps1

    # Uninstall
    .\install.ps1 -Uninstall

.NOTES
    Requires Python 3.11+ and git.
    https://github.com/phlx0/postmortem
#>

[CmdletBinding()]
param(
    [switch]$Uninstall
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# -- Config -------------------------------------------------------------------
$InstallDir  = if ($env:POSTMORTEM_HOME) { $env:POSTMORTEM_HOME } else { Join-Path $HOME '.postmortem' }
$BinDir      = if ($env:POSTMORTEM_BIN)  { $env:POSTMORTEM_BIN  } else { Join-Path $HOME '.local\bin' }
$RepoUrl     = 'https://github.com/phlx0/postmortem'
$PyPiName    = 'postmortem'
$WrapperPath = Join-Path $BinDir 'postmortem.ps1'

# -- Output helpers -----------------------------------------------------------
function Write-Info    { param([string]$Msg) Write-Host "  -> $Msg" -ForegroundColor Cyan }
function Write-Success { param([string]$Msg) Write-Host "  v  $Msg" -ForegroundColor Green }
function Write-Warn    { param([string]$Msg) Write-Host "  !  $Msg" -ForegroundColor Yellow }
function Write-Fail {
    param([string]$Msg)
    Write-Host "  x  $Msg" -ForegroundColor Red
    exit 1
}

# -- Python detection ---------------------------------------------------------
function Find-Python {
    $candidates = @('python3.12', 'python3.11', 'python3', 'python')
    foreach ($cmd in $candidates) {
        $found = Get-Command $cmd -ErrorAction SilentlyContinue
        if (-not $found) { continue }
        try {
            $ver = & $cmd -c 'import sys; print(sys.version_info >= (3,11))' 2>$null
            if ($ver -eq 'True') { return $cmd }
        } catch {
            continue
        }
    }
    return $null
}

function Assert-Git {
    if (-not (Get-Command 'git' -ErrorAction SilentlyContinue)) {
        Write-Fail 'git is required but was not found. Install it from https://git-scm.com'
    }
}

function Assert-Python {
    $script:Python = Find-Python
    if (-not $script:Python) {
        Write-Fail 'Python 3.11+ is required. Install it from https://python.org'
    }
}

# -- PATH management ----------------------------------------------------------
function Update-UserPath {
    $currentPath = [System.Environment]::GetEnvironmentVariable('PATH', 'User')
    if ($currentPath -notlike "*$BinDir*") {
        $newPath = "$BinDir;$currentPath"
        [System.Environment]::SetEnvironmentVariable('PATH', $newPath, 'User')
        $env:PATH = "$BinDir;$env:PATH"
        Write-Success "Added $BinDir to your user PATH (takes effect in new terminals)"
    } else {
        Write-Success "$BinDir is already on your PATH - you are ready!"
    }
}

# -- Wrapper script -----------------------------------------------------------
function Write-Wrapper {
    # The venv's Scripts\ folder already contains a postmortem.exe generated
    # by pip. We just write a tiny .ps1 shim that forwards to it so the
    # plain name "postmortem" works in PowerShell without needing .exe.
    $venvExe = Join-Path $InstallDir 'Scripts\postmortem.exe'
    $null = New-Item -ItemType Directory -Force -Path $BinDir

    $line1 = '# Auto-generated by postmortem installer - do not edit manually.'
    $line2 = "& '$venvExe' @args"
    $line3 = 'exit $LASTEXITCODE'
    $wrapperContent = "$line1`n$line2`n$line3`n"

    Set-Content -Path $WrapperPath -Value $wrapperContent -Encoding UTF8
    Write-Success "Wrapper written: $WrapperPath"
}

# -- Install ------------------------------------------------------------------
function Invoke-Install {
    Write-Info "Installing postmortem into $InstallDir ..."

    & $script:Python -m venv $InstallDir
    if ($LASTEXITCODE -ne 0) { Write-Fail 'Failed to create virtualenv.' }
    Write-Success "Created virtualenv: $InstallDir"

    $pip    = Join-Path $InstallDir 'Scripts\pip.exe'
    $python = Join-Path $InstallDir 'Scripts\python.exe'

    & $python -m pip install --quiet --upgrade pip
    if ($LASTEXITCODE -ne 0) { Write-Fail 'Failed to upgrade pip.' }

    # Ensure build tools are present (required for editable installs)
    & $pip install --quiet --upgrade setuptools wheel
    if ($LASTEXITCODE -ne 0) { Write-Fail 'Failed to install build tools.' }

    # Dev/editable mode if running from a local clone
    $scriptDir = Split-Path -Parent $MyInvocation.ScriptName
    $pyproject  = Join-Path $scriptDir 'pyproject.toml'

    if (Test-Path $pyproject) {
        Write-Info 'Local source detected - installing in editable mode'
        & $pip install --quiet --no-build-isolation -e $scriptDir
        if ($LASTEXITCODE -ne 0) { Write-Fail 'Editable install failed.' }
        Write-Success 'Installed in editable mode (changes apply instantly)'
    } else {
        Write-Info "Installing $PyPiName from PyPI ..."
        & $pip install --quiet $PyPiName
        if ($LASTEXITCODE -ne 0) { Write-Fail "pip install $PyPiName failed." }
        Write-Success "Installed $PyPiName from PyPI"
    }

    Write-Wrapper
    Update-UserPath
}

# -- Uninstall ----------------------------------------------------------------
function Invoke-Uninstall {
    Write-Info 'Removing postmortem ...'

    if (Test-Path $InstallDir) {
        Remove-Item -Recurse -Force $InstallDir
        Write-Success "Removed $InstallDir"
    } else {
        Write-Warn "$InstallDir not found - skipping"
    }

    if (Test-Path $WrapperPath) {
        Remove-Item -Force $WrapperPath
        Write-Success "Removed $WrapperPath"
    }

    $currentPath = [System.Environment]::GetEnvironmentVariable('PATH', 'User')
    if ($currentPath -like "*$BinDir*") {
        $cleaned = ($currentPath -split ';' | Where-Object { $_ -ne $BinDir }) -join ';'
        [System.Environment]::SetEnvironmentVariable('PATH', $cleaned, 'User')
        Write-Success "Removed $BinDir from user PATH"
    }

    Write-Success 'postmortem uninstalled.'
}

# -- Execution policy hint ----------------------------------------------------
function Test-ExecutionPolicy {
    $policy = Get-ExecutionPolicy -Scope CurrentUser
    if ($policy -in @('Restricted', 'AllSigned')) {
        Write-Warn "Your PowerShell execution policy is '$policy'."
        Write-Warn 'To allow local scripts, run:'
        Write-Host ''
        Write-Host '    Set-ExecutionPolicy -Scope CurrentUser -ExecutionPolicy RemoteSigned' -ForegroundColor Yellow
        Write-Host ''
    }
}

# -- Main ---------------------------------------------------------------------
function Main {
    Write-Host ''
    Write-Host '  postmortem - incident timeline builder' -ForegroundColor White
    Write-Host "  $RepoUrl" -ForegroundColor Cyan
    Write-Host ''

    if ($Uninstall) {
        Invoke-Uninstall
        return
    }

    Assert-Python
    Assert-Git
    Test-ExecutionPolicy
    Invoke-Install

    Write-Host ''
    Write-Success 'Done! Open a new terminal and try:'
    Write-Host '     postmortem --since 2h' -ForegroundColor White
    Write-Host ''
}

Main
